pipeline {
    agent any

    environment {
        VENV_DIR = '.venv'
        ALPHAVANTAGE_API_KEY = credentials('alpha_vantage_key')
    }

    stages {
        stage('Clone Git Repo') {
            steps {
                git url: 'https://github.com/khit-mle/mlops-practice.git', branch: 'main'
            }
        }

        stage('Setup Python Virtual Environment') {
            steps {
                script {
                    sh "python3 -m venv ${VENV_DIR}"
                }
            }
        }

        stage('Install Requirements') {
            steps {
                script {
                    sh """
                        . ${VENV_DIR}/bin/activate
                        pip install -r requirements.txt
                    """
                }
            }
        }

        stage('Gather Data') {
            steps {
                script {
                    sh """
                        . ${VENV_DIR}/bin/activate
                        python3 lab2/gather_data.py
                    """
                }
            }
        }

        stage('Process Data') {
            steps {
                script {
                    sh """
                        . ${VENV_DIR}/bin/activate
                        python3 lab2/process_data.py
                    """
                }
            }
        }

        stage('Train Model') {
            steps {
                script {
                    sh """
                        . ${VENV_DIR}/bin/activate
                        python3 lab2/train_model.py
                    """
                }
            }
        }

        stage('Test Model') {
            steps {
                script {
                    sh """
                        . ${VENV_DIR}/bin/activate
                        python3 lab2/test_model.py
                    """
                }
            }
        }
    }

    post {
        always {
            // Clean up the virtual environment and workspace
            deleteDir()
        }
    }
}